# Generated by Django 5.2.5 on 2025-08-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
